name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run build
    - run: make build
    - run: make run
    - run: npm install -g @vscode/vsce
    - run: vsce publish --no-update-package-json "$VSCE_VERSION"
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        VSCE_VERSION: ${{ github.event.release.tag_name }}
